### ISSUE TITLE
老哥 你springboot也会搞啊，能不能加个联系方式，我从油猴脚本来的

### ISSUE THREAD

**Issue by javatoai** [yangfeng20/smart-config#1]

**Comment by yangfeng20** [comment]
可以的，你加我微信吧 y_distance_poem

**Comment by Louis24** [comment]
多条打招呼是怎么做到的啊

**Comment by yangfeng20** [comment]
![image](https://github.com/user-attachments/assets/c9222e11-9e5a-4382-9666-ea9b5e0ebbfe)
zh这里多调用几次send方法
